### ISSUE TITLE
Missing sections

### ISSUE THREAD

**Issue by osaid202** [stungeye/Full-Stack-Notes#6]
Before Filters to Autoload From the Database
and
Helper Methods to Preload "Global" Data
are empty

**Comment by stungeye** [comment]
Thanks for pointing this out. I've added content to these sections:

* [Before Filters to Autoload From the Database](https://stungeye.github.io/Full-Stack-Notes/docs/06-rails-tips-and-tricks/07-session-and-life-cycle.html#before-filters-to-autoload-from-the-database)
* [Helper Methods to Preload "Global" Data](https://stungeye.github.io/Full-Stack-Notes/docs/06-rails-tips-and-tricks/07-session-and-life-cycle.html#helper-methods-to-preload-global-data)
